"""
Per-PC agent configuration. config.json is NOT committed/shared between
machines -- each of the 5 client PCs gets its own copy with a unique
client_id + api_key (generated by the manager, see manager/config/clients.json)
and the manager's LAN address.

If config.json is missing, we write a placeholder template and raise, so a
misconfigured install fails loudly at startup instead of silently reporting
nothing.
"""

import json
import socket
from pathlib import Path

from paths import base_dir

CONFIG_PATH = base_dir() / "config.json"

_TEMPLATE = {
    "client_id": "pc1",
    "api_key": "REPLACE_ME_WITH_KEY_FROM_MANAGER",
    "manager_url": "https://192.168.1.10:8443/api/report",
    "verify_ssl": True,
    "ca_cert_path": "",
    "report_interval_seconds": 30,
    "exclude_remote_ports": [8443],
}


class Config:
    def __init__(self, data: dict):
        self.client_id = data["client_id"]
        self.api_key = data["api_key"]
        self.manager_url = data["manager_url"]
        self.verify_ssl = data.get("verify_ssl", True)
        ca_cert_path = data.get("ca_cert_path") or None
        if ca_cert_path and not Path(ca_cert_path).is_absolute():
            ca_cert_path = str(base_dir() / ca_cert_path)
        self.ca_cert_path = ca_cert_path
        self.report_interval_seconds = data.get("report_interval_seconds", 30)
        self.exclude_remote_ports = data.get("exclude_remote_ports", [])
        self.hostname = socket.gethostname()

    @property
    def requests_verify(self):
        """Value to pass as requests(..., verify=...)."""
        if self.ca_cert_path:
            return self.ca_cert_path
        return self.verify_ssl


def load_config() -> Config:
    if not CONFIG_PATH.exists():
        CONFIG_PATH.write_text(json.dumps(_TEMPLATE, indent=2))
        raise RuntimeError(
            f"No config.json found -- wrote a template to {CONFIG_PATH}. "
            "Fill in client_id, api_key (from the manager) and manager_url, then restart."
        )
    data = json.loads(CONFIG_PATH.read_text())
    if data.get("api_key") == _TEMPLATE["api_key"]:
        raise RuntimeError(f"{CONFIG_PATH} still has placeholder values -- edit it first.")
    return Config(data)
